FROM ubuntu:25.10

ARG _ENV_NAME
ARG _DOMAIN
ARG _TIME_ZONE
ARG _LANG
ARG _SERVER_PORT
ARG _PATH_ROOT
ARG _PATH_CERTIFICATE_PEM
ARG _DEVICE

ENV ENV_NAME=${_ENV_NAME}
ENV DOMAIN=${_DOMAIN}
ENV TZ=${_TIME_ZONE}
ENV LANG=${_LANG}
ENV SERVER_PORT=${_SERVER_PORT}
ENV PATH_ROOT=${_PATH_ROOT}
ENV PATH_CERTIFICATE_PEM=${_PATH_CERTIFICATE_PEM}
ENV DEVICE=${_DEVICE}

ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NOWARNINGS=yes
ENV SUDO_FORCE_REMOVE=yes
ENV HISTFILE="/home/node/.bash_history"
ENV NODE_OPTIONS=--use-openssl-ca
ENV NODE_EXTRA_CA_CERTS="${PATH_CERTIFICATE_PEM}"
ENV NPM_CONFIG_USERCONFIG="/home/node/.npmrc"
ENV PATH="${PATH_ROOT}.venv/bin/:${PATH_ROOT}.local/bin/:${PATH}"
ENV PYTHONPATH="${PATH_ROOT}"
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV PIP_DISABLE_PIP_VERSION_CHECK=1
ENV WAYLAND_DISPLAY=wayland-0
ENV XDG_SESSION_TYPE=wayland
ENV XDG_RUNTIME_DIR="/mnt/wslg/runtime-dir/"
ENV ELECTRON_ENABLE_WAYLAND=1
ENV ELECTRON_OZONE_PLATFORM_HINT=auto
ENV OZONE_PLATFORM=wayland
ENV EGL_PLATFORM=wayland
ENV ANGLE_DEFAULT_PLATFORM=egl
ENV DBUS_SESSION_BUS_ADDRESS="unix:path=${XDG_RUNTIME_DIR}bus"
ENV PULSE_SERVER="unix:/mnt/wslg/PulseServer"
ENV LD_LIBRARY_PATH="/usr/lib/wsl/lib/:/usr/local/cuda/lib64/:/usr/local/cuda-12.9/lib64/"
ENV NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=all

COPY ./certificate/ /usr/local/share/ca-certificates/
COPY ./docker/font/ /usr/share/fonts/truetype/noto/
COPY ./docker/font.conf /etc/fonts/local.conf

RUN cd ~ \
    # No root
    && userdel -r ubuntu \
    && groupadd -g 1000 node \
    && useradd -m -u 1000 -g 1000 -d ${PATH_ROOT} -s /bin/bash node \
    && uid="$(id -u node)" \
    && mkdir -p ${PATH_ROOT} /home/node/ /run/user/${uid} /usr/lib/node_modules/npm/ \
    && chown -R node:node ${PATH_ROOT} /home/node/ /run/user/${uid} /usr/lib/node_modules/npm/ \
    && chmod -R 775 ${PATH_ROOT} /home/node/ /usr/lib/node_modules/npm/ \
    && chmod -R 700 /run/user/${uid} \
    # Update
    && echo 'Acquire::Retries "3";' > /etc/apt/apt.conf.d/80-retries \
    && echo 'Acquire::http::No-Cache "true";' > /etc/apt/apt.conf.d/99no-cache \
    && echo 'Acquire::https::No-Cache "true";' >> /etc/apt/apt.conf.d/99no-cache \
    && VERSION_CODENAME=$(grep VERSION_CODENAME= /etc/os-release | cut -d= -f2) \
    && chmod -R 0644 /usr/local/share/ca-certificates/ \
    && apt-get update && apt-get install -y ca-certificates tzdata curl media-types jq gettext-base \
    && update-ca-certificates \
    && ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime && echo ${TZ} > /etc/timezone \
    && echo "text/typescript ts" >> /etc/mime.types \
    # NodeJs
    && curl -fsSL https://deb.nodesource.com/setup_24.x | bash - \
    && apt-get update && apt-get install -y \
    nodejs \
    && npm install -g npm@latest \
    && rm -rf /usr/lib/node_modules/npm/node_modules/brace-expansion \
    && mkdir -p /usr/lib/node_modules/npm/node_modules/brace-expansion \
    && curl -fsSL https://registry.npmjs.org/brace-expansion/-/brace-expansion-5.0.9.tgz | tar -xz --strip-components=1 -C /usr/lib/node_modules/npm/node_modules/brace-expansion \
    && rm -rf /usr/lib/node_modules/npm/node_modules/tar \
    && mkdir -p /usr/lib/node_modules/npm/node_modules/tar \
    && curl -fsSL https://registry.npmjs.org/tar/-/tar-7.5.21.tgz | tar -xz --strip-components=1 -C /usr/lib/node_modules/npm/node_modules/tar \
    # Python
    && apt-get update && apt-get install -y \
    python3-venv \
    python3-pip \
    # Wslg
    && groupadd -g 110 render || true \
    && groupadd -g 44 video || true \
    && usermod -aG 110 node \
    && usermod -aG 44 node \
    && echo "<driconf></driconf>" > /etc/drirc \
    && apt-get update && apt-get install -y \
    libglib2.0-0 \
    libgtk-3-0 \
    libcairo2 \
    libatk-bridge2.0-0 \
    libatspi2.0-0 \
    libxkbcommon0 \
    libfontconfig1 \
    libfreetype6 \
    libnss3 \
    libnspr4 \
    libasound2t64 \
    libgl1 \
    libglx-mesa0 \
    libgl1-mesa-dri \
    libegl1 \
    libegl1-mesa-dev \
    libegl-dev \
    libglvnd-dev \
    libgbm1 \
    mesa-va-drivers \
    mesa-utils-extra \
    libdrm2 \
    libxdamage1 \
    libxfixes3 \
    libxcomposite1 \
    libxrandr2 \
    libwayland-client0 \
    libwayland-egl1 \
    libwayland-cursor0 \
    libgomp1 \
    libatomic1 \
    xdg-utils \
    # Cuda
    && curl -fsSL https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-keyring_1.1-1_all.deb -o cuda-keyring_1.1-1_all.deb \
    && dpkg -i cuda-keyring_1.1-1_all.deb \
    && apt-get update && apt-get install -y \
    cuda-libraries-12-9 \
    libcudnn9-cuda-12 \
    # Upgrade
    && apt-get update \
    && apt-get upgrade -y \
    # Clean
    && apt-get remove --purge -y sudo \
    && rm -f cuda-keyring_1.1-1_all.deb \
    && apt-get clean -y \
    && apt-get autoclean -y \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/*

USER node

WORKDIR ${PATH_ROOT}

CMD ["sh", "-c", "bash ${PATH_ROOT}script/gpu.sh && bash ${PATH_ROOT}script/dbus.sh && bash ${PATH_ROOT}script/pip.sh \"${DEVICE}\" && bash ${PATH_ROOT}script/npm.sh 'execute'"]

EXPOSE ${SERVER_PORT}
