FROM ubuntu:20.04

ARG _ENV_NAME
ARG _DOMAIN
ARG _TIMEZONE
ARG _SERVER_PORT
ARG _PROXY_HTTP
ARG _PROXY_HTTPS
ARG _PROXY_CERTIFICATE

ENV ENV_NAME=${_ENV_NAME}
ENV DOMAIN=${_DOMAIN}
ENV TZ=${_TIMEZONE}
ENV PROXY_HTTP=${_PROXY_HTTP}
ENV PROXY_HTTPS=${_PROXY_HTTPS}
ENV NODE_EXTRA_CA_CERTS=${_PROXY_CERTIFICATE}

ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NOWARNINGS=yes

COPY ./docker/nodejs_18_setup.sh /home/nodejs_18_setup.sh
COPY ./certificate/proxy/* /usr/local/share/ca-certificates/

RUN cd ~ \
    # NodeJs
    && bash /home/nodejs_18_setup.sh \
    && apt-get update && apt-get install -y nodejs \
    # No root
    && groupadd -g 1000 node \
    && useradd -d /home/root/ -s /bin/bash -u 1000 -g 1000 node \
    && mkdir -p /home/root/ /usr/local/lib/node_modules/ \
    && chown -R node:node /home/root/ /usr/local/lib/node_modules/ /usr/local/bin/ \
    && chmod 775 /home/root/ /usr/local/lib/node_modules/ /usr/local/bin/ \
    # Apt
    && apt-get update && apt-get install -y \
    ca-certificates \
    tesseract-ocr \
    libtesseract-dev \
    # Certificate
    && update-ca-certificates \
    # Clean
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean -y \
    && apt-get autoclean -y \
    && apt-get autoremove -y

USER node

WORKDIR /home/root/

CMD tesseract --version \
    && tesseract --list-langs \
    && npm install && npm run execute

EXPOSE ${_SERVER_PORT}
